spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stateDb
    username: root
    password: '#Mugshot23'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  servlet:
    context-path: "/api/v1"