spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${TABLE_NAME}
    username: ${MYSQL_ROOT_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  servlet:
    context-path: "/api/v1"